{ pkgs, inputs }:

let
  python = pkgs.python314.withPackages (
    ps: with ps; [
      mdformat
      mdformat-gfm
      mdformat-myst
      mdformat-tables
    ]
  );
in
with pkgs;
[
  bash-language-server
  bat
  black
  clang-tools
  claude-agent-acp
  claude-code
  cursor-cli
  delta
  dune_3
  elmPackages.elm-language-server
  emmet-ls
  eslint
  fd
  fish-lsp
  flutter
  fzf
  gdb
  git
  gopls
  html-tidy
  icu.dev
  inputs.ledger-formatter.packages.${system}.default
  inputs.matlab-lsp.packages.${system}.default
  inputs.wbproto-beautifier.packages.${system}.default
  inputs.zls.inputs.zig-flake.packages.${system}.default
  inputs.zls.packages.${system}.default
  kotlin-language-server
  lldb
  lua-language-server
  luajitPackages.luarocks
  marksman
  mercurial
  mermaid-cli
  neocmakelsp
  nil
  nodejs
  nushell
  ocamlPackages.ocaml-lsp
  ocamlPackages.ocamlformat
  pyright
  python
  ripgrep
  rubyPackages.solargraph
  rust-analyzer
  silver-searcher
  stdenv.cc
  stylua
  taplo
  texlab
  tinymist
  tmux
  tree-sitter
  typescript
  typescript-language-server
  vim-language-server
  vscode-langservers-extracted
  yaml-language-server
]
