{ pkgs, inputs }:

let
  wbproto = pkgs.tree-sitter.buildGrammar {
    language = "wbproto";
    version = "1.0.0";
    src = inputs.wbproto;
  };
in
pkgs.writeText "treesitter.lua" ''
  local function add_language(name, filetypes, parser)
    if filetypes == nil then
      filetypes = { name }
    end
    vim.treesitter.language.add(name, { path = parser })
    vim.treesitter.language.register(name, filetypes)
    vim.api.nvim_create_autocmd('FileType', { pattern = filetypes, callback = function() vim.treesitter.start() end })
  end

  add_language("wbproto", nil, "${wbproto}/parser")

  add_language("awk", nil, "${pkgs.tree-sitter-grammars.tree-sitter-awk}/parser")
  add_language("bash", nil, "${pkgs.tree-sitter-grammars.tree-sitter-bash}/parser")
  add_language("bibtex", nil, "${pkgs.tree-sitter-grammars.tree-sitter-bibtex}/parser")
  add_language("c", nil, "${pkgs.tree-sitter-grammars.tree-sitter-c}/parser")
  add_language("c_sharp", nil, "${pkgs.tree-sitter-grammars.tree-sitter-c-sharp}/parser")
  add_language("clojure", nil, "${pkgs.tree-sitter-grammars.tree-sitter-clojure}/parser")
  add_language("cmake", nil, "${pkgs.tree-sitter-grammars.tree-sitter-cmake}/parser")
  add_language("commonlisp", nil, "${pkgs.tree-sitter-grammars.tree-sitter-commonlisp}/parser")
  add_language("cpp", nil, "${pkgs.tree-sitter-grammars.tree-sitter-cpp}/parser")
  add_language("css", nil, "${pkgs.tree-sitter-grammars.tree-sitter-css}/parser")
  add_language("csv", nil, "${pkgs.tree-sitter-grammars.tree-sitter-csv}/parser")
  add_language("dart", nil, "${pkgs.tree-sitter-grammars.tree-sitter-dart}/parser")
  add_language("devicetree", nil, "${pkgs.tree-sitter-grammars.tree-sitter-devicetree}/parser")
  add_language("diff", nil, "${pkgs.tree-sitter-grammars.tree-sitter-diff}/parser")
  add_language("dockerfile", nil, "${pkgs.tree-sitter-grammars.tree-sitter-dockerfile}/parser")
  add_language("dtd", nil, "${pkgs.tree-sitter-grammars.tree-sitter-dtd}/parser")
  add_language("elisp", nil, "${pkgs.tree-sitter-grammars.tree-sitter-elisp}/parser")
  add_language("elixir", nil, "${pkgs.tree-sitter-grammars.tree-sitter-elixir}/parser")
  add_language("elm", nil, "${pkgs.tree-sitter-grammars.tree-sitter-elm}/parser")
  add_language("elvish", nil, "${pkgs.tree-sitter-grammars.tree-sitter-elvish}/parser")
  add_language("erlang", nil, "${pkgs.tree-sitter-grammars.tree-sitter-erlang}/parser")
  add_language("fish", nil, "${pkgs.tree-sitter-grammars.tree-sitter-fish}/parser")
  add_language("fortran", nil, "${pkgs.tree-sitter-grammars.tree-sitter-fortran}/parser")
  add_language("fsharp", nil, "${pkgs.tree-sitter-grammars.tree-sitter-fsharp}/parser")
  add_language("ghostty", nil, "${pkgs.tree-sitter-grammars.tree-sitter-ghostty}/parser")
  add_language("git_config", nil, "${pkgs.tree-sitter-grammars.tree-sitter-git-config}/parser")
  add_language("git_rebase", nil, "${pkgs.tree-sitter-grammars.tree-sitter-git-rebase}/parser")
  add_language("gitattributes", nil, "${pkgs.tree-sitter-grammars.tree-sitter-gitattributes}/parser")
  add_language("gitcommit", nil, "${pkgs.tree-sitter-grammars.tree-sitter-gitcommit}/parser")
  add_language("gitignore", nil, "${pkgs.tree-sitter-grammars.tree-sitter-gitignore}/parser")
  add_language("go", nil, "${pkgs.tree-sitter-grammars.tree-sitter-go}/parser")
  add_language("gomod", nil, "${pkgs.tree-sitter-grammars.tree-sitter-gomod}/parser")
  add_language("gotmpl", nil, "${pkgs.tree-sitter-grammars.tree-sitter-gotmpl}/parser")
  add_language("gowork", nil, "${pkgs.tree-sitter-grammars.tree-sitter-gowork}/parser")
  add_language("graphql", nil, "${pkgs.tree-sitter-grammars.tree-sitter-graphql}/parser")
  add_language("groovy", nil, "${pkgs.tree-sitter-grammars.tree-sitter-groovy}/parser")
  add_language("haskell", nil, "${pkgs.tree-sitter-grammars.tree-sitter-haskell}/parser")
  add_language("hjson", nil, "${pkgs.tree-sitter-grammars.tree-sitter-hjson}/parser")
  add_language("hosts", nil, "${pkgs.tree-sitter-grammars.tree-sitter-hosts}/parser")
  add_language("html", nil, "${pkgs.tree-sitter-grammars.tree-sitter-html}/parser")
  add_language("hyprlang", nil, "${pkgs.tree-sitter-grammars.tree-sitter-hyprlang}/parser")
  add_language("ini", nil, "${pkgs.tree-sitter-grammars.tree-sitter-ini}/parser")
  add_language("java", nil, "${pkgs.tree-sitter-grammars.tree-sitter-java}/parser")
  add_language("javascript", nil, "${pkgs.tree-sitter-grammars.tree-sitter-javascript}/parser")
  add_language("jq", nil, "${pkgs.tree-sitter-grammars.tree-sitter-jq}/parser")
  add_language("jsdoc", nil, "${pkgs.tree-sitter-grammars.tree-sitter-jsdoc}/parser")
  add_language("json", nil, "${pkgs.tree-sitter-grammars.tree-sitter-json}/parser")
  add_language("json5", nil, "${pkgs.tree-sitter-grammars.tree-sitter-json5}/parser")
  add_language("julia", nil, "${pkgs.tree-sitter-grammars.tree-sitter-julia}/parser")
  add_language("just", nil, "${pkgs.tree-sitter-grammars.tree-sitter-just}/parser")
  add_language("kdl", nil, "${pkgs.tree-sitter-grammars.tree-sitter-kdl}/parser")
  add_language("kotlin", nil, "${pkgs.tree-sitter-grammars.tree-sitter-kotlin}/parser")
  add_language("latex", nil, "${pkgs.tree-sitter-grammars.tree-sitter-latex}/parser")
  add_language("ledger", nil, "${pkgs.tree-sitter-grammars.tree-sitter-ledger}/parser")
  add_language("lua", nil, "${pkgs.tree-sitter-grammars.tree-sitter-lua}/parser")
  add_language("make", nil, "${pkgs.tree-sitter-grammars.tree-sitter-make}/parser")
  add_language("markdoc", nil, "${pkgs.tree-sitter-grammars.tree-sitter-markdoc}/parser")
  add_language("markdown", nil, "${pkgs.tree-sitter-grammars.tree-sitter-markdown}/parser")
  add_language("matlab", nil, "${pkgs.tree-sitter-grammars.tree-sitter-matlab}/parser")
  add_language("mermaid", nil, "${pkgs.tree-sitter-grammars.tree-sitter-mermaid}/parser")
  add_language("meson", nil, "${pkgs.tree-sitter-grammars.tree-sitter-meson}/parser")
  add_language("nginx", nil, "${pkgs.tree-sitter-grammars.tree-sitter-nginx}/parser")
  add_language("nim", nil, "${pkgs.tree-sitter-grammars.tree-sitter-nim}/parser")
  add_language("nix", nil, "${pkgs.tree-sitter-grammars.tree-sitter-nix}/parser")
  add_language("nu", nil, "${pkgs.tree-sitter-grammars.tree-sitter-nu}/parser")
  add_language("ocaml", nil, "${pkgs.tree-sitter-grammars.tree-sitter-ocaml}/parser")
  add_language("ocamllex", nil, "${pkgs.tree-sitter-grammars.tree-sitter-ocamllex}/parser")
  add_language("odin", nil, "${pkgs.tree-sitter-grammars.tree-sitter-odin}/parser")
  add_language("org", nil, "${pkgs.tree-sitter-grammars.tree-sitter-org}/parser")
  add_language("pascal", nil, "${pkgs.tree-sitter-grammars.tree-sitter-pascal}/parser")
  add_language("passwd", nil, "${pkgs.tree-sitter-grammars.tree-sitter-passwd}/parser")
  add_language("pem", nil, "${pkgs.tree-sitter-grammars.tree-sitter-pem}/parser")
  add_language("perl", nil, "${pkgs.tree-sitter-grammars.tree-sitter-perl}/parser")
  add_language("php", nil, "${pkgs.tree-sitter-grammars.tree-sitter-php}/parser")
  add_language("phpdoc", nil, "${pkgs.tree-sitter-grammars.tree-sitter-phpdoc}/parser")
  add_language("powershell", nil, "${pkgs.tree-sitter-grammars.tree-sitter-powershell}/parser")
  add_language("prolog", nil, "${pkgs.tree-sitter-grammars.tree-sitter-prolog}/parser")
  add_language("properties", nil, "${pkgs.tree-sitter-grammars.tree-sitter-properties}/parser")
  add_language("proto", nil, "${pkgs.tree-sitter-grammars.tree-sitter-proto}/parser")
  add_language("python", nil, "${pkgs.tree-sitter-grammars.tree-sitter-python}/parser")
  add_language("qmljs", nil, "${pkgs.tree-sitter-grammars.tree-sitter-qmljs}/parser")
  add_language("query", nil, "${pkgs.tree-sitter-grammars.tree-sitter-query}/parser")
  add_language("r", nil, "${pkgs.tree-sitter-grammars.tree-sitter-r}/parser")
  add_language("regex", nil, "${pkgs.tree-sitter-grammars.tree-sitter-regex}/parser")
  add_language("ruby", nil, "${pkgs.tree-sitter-grammars.tree-sitter-ruby}/parser")
  add_language("rust", nil, "${pkgs.tree-sitter-grammars.tree-sitter-rust}/parser")
  add_language("scala", nil, "${pkgs.tree-sitter-grammars.tree-sitter-scala}/parser")
  add_language("scheme", nil, "${pkgs.tree-sitter-grammars.tree-sitter-scheme}/parser")
  add_language("scss", nil, "${pkgs.tree-sitter-grammars.tree-sitter-scss}/parser")
  add_language("sql", nil, "${pkgs.tree-sitter-grammars.tree-sitter-sql}/parser")
  add_language("svelte", nil, "${pkgs.tree-sitter-grammars.tree-sitter-svelte}/parser")
  add_language("sway", nil, "${pkgs.tree-sitter-grammars.tree-sitter-sway}/parser")
  add_language("swift", nil, "${pkgs.tree-sitter-grammars.tree-sitter-swift}/parser")
  add_language("toml", nil, "${pkgs.tree-sitter-grammars.tree-sitter-toml}/parser")
  add_language("tsx", nil, "${pkgs.tree-sitter-grammars.tree-sitter-tsx}/parser")
  add_language("typescript", nil, "${pkgs.tree-sitter-grammars.tree-sitter-typescript}/parser")
  add_language("typst", nil, "${pkgs.tree-sitter-grammars.tree-sitter-typst}/parser")
  add_language("v", nil, "${pkgs.tree-sitter-grammars.tree-sitter-v}/parser")
  add_language("vala", nil, "${pkgs.tree-sitter-grammars.tree-sitter-vala}/parser")
  add_language("verilog", nil, "${pkgs.tree-sitter-grammars.tree-sitter-verilog}/parser")
  add_language("vhdl", nil, "${pkgs.tree-sitter-grammars.tree-sitter-vhdl}/parser")
  add_language("vim", nil, "${pkgs.tree-sitter-grammars.tree-sitter-vim}/parser")
  add_language("vue", nil, "${pkgs.tree-sitter-grammars.tree-sitter-vue}/parser")
  add_language("xml", nil, "${pkgs.tree-sitter-grammars.tree-sitter-xml}/parser")
  add_language("yaml", nil, "${pkgs.tree-sitter-grammars.tree-sitter-yaml}/parser")
  add_language("zig", nil, "${pkgs.tree-sitter-grammars.tree-sitter-zig}/parser")
''
